### ISSUE TITLE
ReactLiveClock: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by MrUltimate** [pvoznyuk/react-live-clock#235]
Hello there,

Thanks for this package. I'm currently trying to use this with NextJS 13 and using the latest version available `6.1.3`

I'm getting the follow error thrown in console:

```
react-dom.development.js?160d:94 Warning: ReactLiveClock: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    at ReactLiveClock (webpack-internal:///./node_modules/react-live-clock/lib/Component.js:30:24)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:30:19750)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:30:19750)
    at header
    at VisualElementHandler (webpack-internal:///./node_modules/framer-motion/dist/es/motion/utils/VisualElementHandler.mjs:8:1)
    at MotionComponent (webpack-internal:///./node_modules/framer-motion/dist/es/motion/index.mjs:50:65)
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:30:19750)
    at Header
    at PopChildMeasure (webpack-internal:///./node_modules/framer-motion/dist/es/components/AnimatePresence/PopChild.mjs:13:1)
    at PopChild (webpack-internal:///./node_modules/framer-motion/dist/es/components/AnimatePresence/PopChild.mjs:33:21)
    at PresenceChild (webpack-internal:///./node_modules/framer-motion/dist/es/components/AnimatePresence/PresenceChild.mjs:15:26)
    at AnimatePresence (webpack-internal:///./node_modules/framer-motion/dist/es/components/AnimatePresence/index.mjs:72:28)
    at Fe (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:30:17299)
    at ThemeContext (webpack-internal:///./app/styles/ThemeContext.js:16:11)
    at StyledComponentsRegistry (webpack-internal:///./app/styles/Registry.js:19:11)
    at body
    at html
    at RootLayout (webpack-internal:///./app/layout.jsx:18:11)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/client/components/react-dev-overlay/internal/ReactDevOverlay.js:53:9)
    at HotReload (webpack-internal:///./node_modules/next/dist/client/components/react-dev-overlay/hot-reloader-client.js:19:11)
    at Router (webpack-internal:///./node_modules/next/dist/client/components/app-router.js:96:11)
    at ErrorBoundaryHandler (webpack-internal:///./node_modules/next/dist/client/components/error-boundary.js:28:9)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/client/components/error-boundary.js:40:11)
    at AppRouter
    at ServerRoot (webpack-internal:///./node_modules/next/dist/client/app-index.js:113:11)
    at RSCComponent
    at Root (webpack-internal:///./node_modules/next/dist/client/app-index.js:130:11)
```

This is how I've implemented it in my component:

```
<Clock
    format={'hh:mm A'}
    ticking={true}
      timezone={'America/New_York'}
      noSsr
/>
```

**Comment by anthony0030** [comment]
Hi @MrUltimate, This is what's called a deprecation warning (not an error).
It is saying that in a later version of the software you are using, a particular function (defaultProps) will stop working.
It is also giving a solution (Use JavaScript default parameters).
When I have some time I will convert my usage of default props to JavaScript default parameters.
You have done nothing wrong, also the code should still work regardless of the warning.

Thank you @MrUltimate for bringing this to my attention.

**Comment by anthony0030** [comment]
Hi @MrUltimate react-live-clock@6.1.5 should fix this problem :)
