### ISSUE TITLE
Change Timezone

### ISSUE THREAD

**Issue by janscherer** [pvoznyuk/react-live-clock#42]
Is it possible to change the timezone? I tried to use a state-variable but the clock does not update on timezone changes. The following however seems to work:

`<Clock key={clockTimezone} format={"HH:mm:ss"} ticking={true} timezone={clockTimezone} />
`

Unfortunately I receive the following error message in console:

> Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function

**Comment by anthony0030** [comment]
Do you have an example you could show me, please?

**Comment by Nikhiladiga** [comment]
In this.props.timezone i get the string US/Pacific. This does not seem to change the time as the prop changes.
`<Clock format={'HH:mm:ss'} ticking={true} timezone={this.props.timezone}/>`

**Comment by kershnerd** [comment]
Same with me...  When timezone changes after the Clock component is already mounted and displayed causes what the OP stated:
>Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function

**Comment by kershnerd** [comment]
I also see the same issue.  My app sets the default timezone and the clock is rendered correctly.  Later in the app, redux updates the timezone but the clock's time is unchanged.

It appears that it is not possible to change the timezone once the clock is displaying.

**Comment by kershnerd** [comment]
... and because I can't change timezone dynamically, I'm out!

**Comment by anthony0030** [comment]
Sorry for the delays. I have been having problems with my computer and I am trying to resolve them still.
I can't get the project to boot-up due to an error:

```
➜  react-live-clock git:(master) ✗ npm start dev

> react-live-clock@4.0.5 start /Users/anthonyveaudry/Sites/react-live-clock
> react-component-template "dev"

nps executing: cross-env NODE_ENV=development webpack-dev-server
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1495:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'localhost'
}
The script called "dev" which runs "cross-env NODE_ENV=development webpack-dev-server" failed with exit code 1 https://github.com/kentcdodds/p-s/blob/v3.1.0/other/ERRORS_AND_WARNINGS.md#failed-with-exit-code
```




Any pull requests are welcome. have you tried adding this component in a div with a key that contains the time zone?

**Comment by anthony0030** [comment]
Good morning,

This problem should be resolved in version 5.0.0-beta1

Please take a look and let me know by the end of the week.

**Comment by anthony0030** [comment]
Closing due to inactivity.

**Comment by maoryadin** [comment]
The dependency of react-moment have made some issue on production.
from some reason its throw exception.

**Comment by anthony0030** [comment]
Are you missing a dependency in production?
